// Admin
// auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_TOKEN = 'FETCH_TOKEN';
export const REMEMBER_USER = 'REMEMBER_USER';
export const UN_REMEMBER_USER = 'UN_REMEMBER_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
// users
export const LOAD_USERS = 'LOAD_USERS';
export const RECEIVE_USERS = 'REDCIVE_USERS';
// goods
export const LOAD_GOODS = 'LOAD_GOODS';
export const RECEIVE_GOODS = 'RECEIVE_GOODS';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAILURE = 'CREATE_FAILURE';
// category first
export const LOAD_CATEGORIES_FIRST = 'LOAD_CATEGORIES_FIRST';
export const FINISH_CATEGORIES_FIRST = 'FINISH_CATEGORIES_FIRST';
export const CREATE_CATEGORY_FIRST = 'CREATE_CATEGORY_FIRST';
// category second
export const LOAD_CATEGORIES_SECOND = 'LOAD_CATEGORIES_SECOND';
export const FINISH_CATEGORIES_SECOND = 'FINISH_CATEGORIES_SECOND';
export const CREATE_CATEGORY_SECOND = 'CREATE_CATEGORY_SECOND';
// service
export const SERVICE_START = 'SERVICE_START';
export const SERVICE_END = 'SERVICE_END';
// order
export const LOAD_ORDERS = 'LOAD_ORDERS';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const STATISTICS_ORDER = 'STATISTICS_ORDER'; // 订单统计
export const ORDER_SERVICE_START = 'ORDER_SERVICE_START';
export const ORDER_SERVICE_END = 'ORDER_SERVICE_END';
// admin
export const LOAD_ADMIN_INFO = 'LOAD_ADMIN_INFO';
export const LOAD_ADMIN_INFO_SUCCESS = 'LOAD_ADMIN_INFO_SUCCESS';
export const LOAD_ADMIN_INFO_FAILURE = 'LOAD_ADMIN_INFO_FAILURE';
// advs
export const LOAD_ADVS = 'LOAD_ADVS';
export const LOAD_ADVS_SUCCESS = 'LOAD_ADVS_SUCCESS';
export const LOAD_ADVS_FAILURE = 'LOAD_ADVS_FAILURE';
